name: Test Build

on:
  push:
    branches: [dev]
    tags: ['v*']
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
      
      - name: Install uv 
        uses: astral-sh/setup-uv@v4
      
      - name: Install dependencies
        run: |
          uv sync --dev --locked --all-extras
      
      - name: Run tests (small dataset)
        run: |
          uv run --isolated --no-project --with dist/*.whl pytest -m "not large"
          uv run --isolated --no-project --with dist/*.tar.gz pytest -m "not large"
        env:
          TEST_SIZE: small